version: '3'
services:
  promcontainer:
    container_name: prometheus
    image: "prom/prometheus"
    volumes:
      - ./prometheus/:/etc/prometheus/
#      - prometheus_data:/prometheus
    ports:
      - "9090:9090"  
  grafanacontainer:
    container_name: grafana
    image: "grafana/grafana"
    ports:
      - "3000:3000"
